# Generated by Django 5.2.4 on 2025-07-24 15:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invite_users',
            field=models.ManyToManyField(related_name='invite_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
