# Generated by Django 5.2.4 on 2025-07-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invite_status_code',
            field=models.BooleanField(blank=True, default=False, verbose_name='Статус активации кода'),
        ),
    ]
