# Generated by Django 5.2.4 on 2025-07-25 11:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_invite_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='invite_users',
            field=models.ManyToManyField(related_name='invite_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
